- hosts: localhost
  connection: local
  gather_facts: no
  sudo: no
  roles:
    - homebrew
    - homebrew-cask
    - ruby-build
  vars:
    # Tap external Homebrew repositories.
    #
    # e.g.
    # - homebrew/binary
    homebrew_repositories:

    # Managed Homebrew packages.
    #
    # e.g.
    # - package_name
    # or
    # { name: package_name, state: package_state, install_options: [with-baz, enable-debug] }
    #
    # state choices: [head, latest, present, absent, linked, unlinked] (default: latest)
    # install_options: string or sequence (default: none)
    homebrew_packages:
      - readline
      - openssl
      - { name: openssl, state: linked, install_options: force }
      - ansible
      - git
      - git-flow
      - heroku-toolbelt
      - emacs
      - mysql
      - postgresql
      - autoconf
      - cask
      - memcached
      - direnv
      - elasticsearch
      - pwgen
      - go
      - hub
      - hugo
      - tmux
      - peco
      - nvm
      - rbenv
      - rbenv-gem-rehash
      - ruby-build
      - vim
      - bash
      - bash-completions


    # Tap external Homebrew Cask repositories.
    homebrew_cask_repositories:
      - caskroom/versions

    # Managed Homebrew Cask packages.
    #
    # e.g.
    # - package_name
    # or
    # { name: package_name, state: package_state }
    #
    # state choices: [present, absent, installed, uninstalled] (default: present)
    homebrew_cask_packages:
      - firefox-ja
      - flash
      - google-chrome
      - iterm2
      - java6
      - karabiner
      - slack
      - sublime-text
      - vagrant
      - virtualbox
      - alfred
      - spark
      - psequel
      - aquaskk
      - fluid
      - nvalt
      - dropbox
      - vlc
      - flux
      - gyazo
      - filezilla
#     - bettersnaptool
#     - 1password ver3
#     - marked2
#     - sunrise
#     - yorufukurou