---
- name: Installs latest stable version of Ruby
  shell: rbenv install -s $(rbenv install -l | grep -v - | tail -1)
  register: result
  changed_when: '"Installed ruby" in result.stderr'

- name: Switch to latest stable version of Ruby
  shell: rbenv global $(rbenv install -l | grep -v - | tail -1)

- name: Installs using version of Ruby
  shell: rbenv install $item
  with_itmes:
    - 2.2.2
    - 2.2.0
  register: result
  changed_when: '"Installed ruby" in result.stderr'

- name: Installs latest available version of bundler.
  gem: name=bundler state=latest
